<%@ Page Language="VB" AutoEventWireup="false" CodeFile="AddRoyalties.aspx.vb" Inherits="AddRoyalties" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 73px;
        }
    </style>
</head>
<body style="height: 212px">
    <form id="form1" runat="server" style="text-align:center; background-color:cadetblue">
        <h1>
            <u>Update Royalites</u><br />
        </h1>
        <table align="center" style="text-align:center; background-color:aquamarine; border:double" id="table_Royalty">
            <tr>
                <td>       AID        </td>
                <td>       PID        </td>
                <td>       ROYALTY    </td>
                <td>       UPDATE     </td>
                <td class="auto-style1"> DELETE </td>
            </tr>
        </table>

        <%--<p>
            
            <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource2" AutoGenerateColumns="False" Height="183px" Width="886px" AutoGenerateDeleteButton="True" BackColor="#CCFF33">
                <Columns>
                    <asp:BoundField DataField="AID" HeaderText="AID" InsertVisible="False" SortExpression="AID" />
                    <asp:BoundField DataField="PID" HeaderText="PID" InsertVisible="False" SortExpression="PID" />
                    <asp:BoundField DataField="Royalty" HeaderText="Royalty" SortExpression="Royalty" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:Author %>" ProviderName="<%$ ConnectionStrings:Author.ProviderName %>" SelectCommand="SELECT Authors.AID, Publishers.PID, Royalties.Royalty
FROM Publishers INNER JOIN (Authors INNER JOIN Royalties ON Authors.[AID] = Royalties.[AID]) ON Publishers.[PID] = Royalties.[PID];
" DeleteCommand="DELETE FROM Royalties WHERE AID = @pAID and PID = @pPID">
                <DeleteParameters>
                    <asp:Parameter DefaultValue="" Name="pAID" />
                    <asp:Parameter DefaultValue="" Name="pPID" />
                </DeleteParameters>
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>
        </p>--%>
        
        <p>
            <asp:Button ID="Button1" runat="server" style="margin-left: 0px" Text="Submit" />
        </p>
        <p>
            <asp:Label ID="greet" runat="server" Text=""></asp:Label>
        </p>
    </form>
</body>
</html>
